export const ESG_FRAMEWORKS: string[] = [
  "VSME (Voluntary Sustainability Reporting Standard for SMEs)",
  "ESRS (European Sustainability Reporting Standards)",
  "GRI (Global Reporting Initiative)",
  "IFRS S1 – General Requirements for Sustainability-related Financial Disclosures",
  "IFRS S2 – Climate-related Disclosures",
  "SASB Standards (Sustainability Accounting Standards Board)",
  "Integrated Reporting (<IR>) Framework",
  "CDP (Carbon Disclosure Project)",
  "GHG Protocol",
  "TCFD (Task Force on Climate-related Financial Disclosures)",
  "TNFD (Taskforce on Nature-related Financial Disclosures)",
  "CDSB (Climate Disclosure Standards Board – now consolidated into IFRS Foundation)",
  "UN Global Compact (UNGC)",
  "UN Sustainable Development Goals (SDGs)",
  "OECD Guidelines for Multinational Enterprises",
  "AA1000 Series (AccountAbility Standards)",
  "ISO 14001 (Environmental Management Systems)",
  "ISO 26000 (Social Responsibility)",
  "ISO 50001 (Energy Management Systems)",
  "ISO 45001 (Occupational Health & Safety)",
  "SA8000 (Social Accountability Standard)",
  "Eco-Management and Audit Scheme (EMAS)"
];
